spring:
  application:
    name: backend
  datasource:
    url: "${DB_URL}"
    username: "weather_db_owner"
    password: "1RKIPdo8uAvT"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT}
